PLUGIN_NAME := hyprtail

SOURCE_FILES := $(wildcard src/*.cpp)
HEADER_FILES := $(wildcard src/*.hpp)
# Embedded into the plugin with #embed (src/ShaderSource.cpp).
SHADER_FILES := $(wildcard shaders/*.vert shaders/*.frag shaders/hyprtail/*.glsl)
OBJECT_FILES := $(patsubst src/%.cpp, out/%.o, $(SOURCE_FILES))

OUTPUT := out/$(PLUGIN_NAME).so

# Two ways to get Hyprland's headers:
#
#   make          Default, used by hyprpm and users. Headers from pkg-config.
#                 Under hyprpm, PKG_CONFIG_PATH points at the headers hyprpm
#                 built for the running Hyprland; otherwise the installed
#                 package's (e.g. /usr/include/hyprland).
#   make DEV=1    Development. Headers from the external/Hyprland checkout,
#                 which must be at the pinned commit and built (SPEC §2).
DEV ?= 0

# Pinned Hyprland commit (SPEC §2). Tracks the host package: v0.56.2.
HYPRLAND_PIN   := efb50993780079460b0cbed1363e2166a2de1d9f
HYPRLAND_SRC   := $(CURDIR)/external/Hyprland
HOST_VERSION_H := /usr/include/hyprland/src/version.h

ifeq ($(DEV),1)
    HEADER_CHECK    := check-pin
    # pkg-config brings in the pixman/drm/cairo/freetype includes that
    # hyprland.pc would otherwise provide.
    HYPRLAND_CFLAGS := -I$(HYPRLAND_SRC)/src -I$(HYPRLAND_SRC)/protocols $(shell pkg-config --cflags pixman-1 libdrm cairo freetype2)
else
    HEADER_CHECK    := check-headers
    HYPRLAND_CFLAGS := $(shell pkg-config --cflags hyprland 2>/dev/null)
endif

# Appended, not assigned: hyprpm passes extra CFLAGS/CXXFLAGS through the
# environment (hyprpm PluginManager.cpp getPluginBuildEnv).
CXXFLAGS += -Wall -Wno-missing-field-initializers -fPIC -std=c++26 -g $(HYPRLAND_CFLAGS)

# GCC marks some template statics STB_GNU_UNIQUE, which makes dlclose a no-op
# and breaks plugin unload/reload. Checked by compiler identity, not by name,
# so CXX=c++ still gets it.
ifneq ($(shell $(CXX) --version 2>/dev/null | grep -c "Free Software Foundation"),0)
    CXXFLAGS += --no-gnu-unique
endif

.PHONY: all clean load unload check-pin check-headers

all: $(OUTPUT)

$(OUTPUT): $(OBJECT_FILES)
	$(CXX) -shared $^ $(LDFLAGS) -o $@

out/%.o: src/%.cpp $(HEADER_FILES) $(SHADER_FILES) | $(HEADER_CHECK)
	@mkdir -p out
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Default mode: fail clearly if pkg-config can't find Hyprland's headers, and
# warn (don't fail) if they're not the commit this plugin is developed
# against: it may still build and work, or not (no ABI stability across
# Hyprland commits).
check-headers:
	@if ! pkg-config --exists hyprland; then \
		echo "error: Hyprland headers not found by pkg-config (hyprland.pc)." >&2; \
		echo "       Install your distribution's Hyprland development headers, build with hyprpm, or use 'make DEV=1'." >&2; \
		exit 1; \
	fi
	@found=""; \
	for d in $$(pkg-config --cflags-only-I hyprland | sed 's/-I//g'); do \
		if [ -f "$$d/version.h" ]; then found=$$(sed -n 's/^#define GIT_COMMIT_HASH *"\(.*\)"/\1/p' "$$d/version.h"); break; fi; \
	done; \
	if [ -n "$$found" ] && [ "$$found" != "$(HYPRLAND_PIN)" ]; then \
		echo "warning: building against Hyprland $$found; hyprtail is developed against $(HYPRLAND_PIN) (v0.56.2) and may not build or work with other versions" >&2; \
	fi

# DEV=1: fails if external/Hyprland isn't checked out at the pin or hasn't
# been built (version.h and protocol headers are generated by its build).
# Warns if the installed host headers moved off the pin, e.g. after a package
# upgrade: the plugin would then fail the ABI hash check when loaded into the
# host.
check-pin:
	@head=$$(git -C $(HYPRLAND_SRC) rev-parse HEAD 2>/dev/null); \
	if [ "$$head" != "$(HYPRLAND_PIN)" ]; then \
		echo "error: external/Hyprland is at '$$head', pin is $(HYPRLAND_PIN) (SPEC §2)" >&2; exit 1; \
	fi
	@if [ ! -f $(HYPRLAND_SRC)/src/version.h ]; then \
		echo "error: $(HYPRLAND_SRC)/src/version.h missing, run 'make clear && make debug' in external/Hyprland" >&2; exit 1; \
	fi
	@if [ -f $(HOST_VERSION_H) ] && ! grep -q '"$(HYPRLAND_PIN)"' $(HOST_VERSION_H); then \
		echo "warning: installed Hyprland headers ($(HOST_VERSION_H)) are not at the pin; host package moved? re-pin before loading on the host" >&2; \
	fi

clean:
	$(RM) -r out/

# These talk to whichever Hyprland instance $HYPRLAND_INSTANCE_SIGNATURE
# points at: run them from a terminal inside the instance you mean.
load: all
	hyprctl plugin load $(CURDIR)/$(OUTPUT)

unload:
	hyprctl plugin unload $(CURDIR)/$(OUTPUT)
