PLUGIN_NAME := hyprtail-stage1

SOURCE_FILES := $(wildcard src/*.cpp)
HEADER_FILES := $(wildcard src/*.hpp)
OBJECT_FILES := $(patsubst src/%.cpp, out/%.o, $(SOURCE_FILES))

HYPRLAND_SRC := $(CURDIR)/external/Hyprland

# Pinned Hyprland commit (SPEC §2). Tracks the host package: v0.56.2.
HYPRLAND_PIN   := efb50993780079460b0cbed1363e2166a2de1d9f
HOST_VERSION_H := /usr/include/hyprland/src/version.h

# Local Hyprland headers first so they override any system-installed version.
# pkg-config brings in pixman/drm/cairo/freetype transitive includes.
CXXFLAGS := -Wall -Wno-missing-field-initializers -fPIC -std=c++26 -g \
    -I$(HYPRLAND_SRC)/src \
    -I$(HYPRLAND_SRC)/protocols \
    $(shell pkg-config --cflags pixman-1 libdrm cairo freetype2)

ifeq ($(CXX),g++)
    CXXFLAGS += --no-gnu-unique
endif

OUTPUT := out/$(PLUGIN_NAME).so

.PHONY: all clean load unload check-pin

all: $(OUTPUT)

$(OUTPUT): $(OBJECT_FILES)
	$(CXX) -shared $^ $(LDFLAGS) -o $@

out/%.o: src/%.cpp $(HEADER_FILES) | check-pin
	@mkdir -p out
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Fails if external/Hyprland isn't checked out at the pin or hasn't been built
# (version.h and protocol headers are generated by its build). Warns if the
# installed host headers moved off the pin, e.g. after a package upgrade: the
# plugin would then fail the ABI hash check when loaded into the host.
check-pin:
	@head=$$(git -C $(HYPRLAND_SRC) rev-parse HEAD 2>/dev/null); \
	if [ "$$head" != "$(HYPRLAND_PIN)" ]; then \
		echo "error: external/Hyprland is at '$$head', pin is $(HYPRLAND_PIN) (SPEC §2)" >&2; exit 1; \
	fi
	@if [ ! -f $(HYPRLAND_SRC)/src/version.h ]; then \
		echo "error: $(HYPRLAND_SRC)/src/version.h missing, run 'make clear && make debug' in external/Hyprland" >&2; exit 1; \
	fi
	@if [ -f $(HOST_VERSION_H) ] && ! grep -q '"$(HYPRLAND_PIN)"' $(HOST_VERSION_H); then \
		echo "warning: installed Hyprland headers ($(HOST_VERSION_H)) are not at the pin; host package moved? re-pin before loading on the host" >&2; \
	fi

clean:
	$(RM) -r out/

load: all
	hyprctl plugin load $(CURDIR)/$(OUTPUT)

unload:
	hyprctl plugin unload $(CURDIR)/$(OUTPUT)
